# Generated by Django 5.0.6 on 2024-06-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime_map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crimedata',
            name='crime_type',
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='murder',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='robbery',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='sexual_crime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='theft',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='crimedata',
            name='violence',
            field=models.IntegerField(),
        ),
    ]
